import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()

ALERT_TARGETS = {
    "NTA":          "info@nta.gov.np",
    "Nepal Police": "cybercrime@nepalpolice.gov.np",
    "NITC":         "info@nitc.gov.np",
}

def send_alert(breach_data, department="NTA"):
    sender    = os.getenv("ALERT_EMAIL")
    password  = os.getenv("ALERT_PASSWORD")
    recipient = ALERT_TARGETS.get(department, sender)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[NepalShield] Breach Alert - Threat Score: {breach_data['score']}/10"
    msg["From"]    = sender
    msg["To"]      = recipient

    body = f"""
NepalShield - Government Data Breach Alert
==========================================

Source      : {breach_data['source']}
Emails Found: {', '.join(breach_data['emails'])}
Threat Score: {breach_data['score']}/10
Keywords    : {', '.join(breach_data['keywords'])}

Raw Data Preview:
{breach_data['raw_text'][:300]}

--
This alert was automatically generated by NepalShield.
Please take immediate action to secure affected accounts.
    """

    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
            print(f"Alert sent to {department} ({recipient})")
    except Exception as e:
        print(f"Alert system ready - email will send when configured: {e}")

if __name__ == "__main__":
    print("Alert system loaded successfully!")
